paas: #Dedicated to compiler
  version: v1

#Custom image, not available in the library
images:
  foo:
    build-name: foo
    tag: lastest
    path: '/images/${FOO}'

#Hook to build the project before container, Called in this order
builds:
  composer-build: #Name of the step
    composer: ${COMPOSER} #Hook to call

#Volume to build to use with container
volumes:
  main: #Name of the volume
    local_path: "/foo/bar" #optional local path where store data in the volume
    add: #folder or file, from .paas.yml where is located to add to the volume
      - 'src'
      - 'vendor'
      - 'composer.json'
      - 'composer.lock'
      - 'composer.phar'
  other_name: #Name of the volume
    add: #folder or file, from .paas.yml where is located to add to the volume
      - 'vendor'

#Pods (set of container)
pods:
  php-pods: #podset name
    replicas: 1 #instance of pods
    containers:
      php-run: #Container name
        image: php-run #Container image to use
        version: 7.4
        listen: #Port listen by the container
          - 8080
        volumes: #Volumes to link
          main:
            from: 'main'
            mount_path: '/path/in/container/' #Path where volume will be mount
          vendor:
            mount_path: '/path/in/container/' #Path where data will be stored
            add: #folder or file, from .paas.yml where is located to add to the volume
              - 'vendor'
        variables:
          SERVER_SCRIPT: '/opt/paas/src/server.php'

#Pods expositions
services:
  php-pods: #Pod name
    - listen: 9876 #Port listened
      target: 8080 #Pod's port targeted
